# Goal
int8 ADD=1
int8 REMOVE=2
int8 action

# xml to add to the urdf
string xml_elements_to_add

# names of the joint and links to remove from the urdf
string[] element_names_to_remove
---
# Result
bool success
---
# Define a feedback message
float32 percent_complete
