# goal
#
# list of descriptions of the objects the client wants the
# the perception system to look for
designator_integration_msgs/Designator[] requests
---
# result
#
# upon termination or cancelation, the vision system sends back
# a (potentially incomplete, in case of cancel) list of descriptions
# of objects it has last seen
designator_integration_msgs/Designator[] percepts
---
# feedback
#
# whenever the vision pipeline ran through, the vision system
# reports a list of descriptions of the objects it has found
designator_integration_msgs/Designator[] percepts
