#Inizio coordinate della kinect, commentare le coordinate non necessarie.

geometry_msgs/Point HEAD_COORD
geometry_msgs/Point NECK_COORD
geometry_msgs/Point SHOULDER_RIGHT_COORD
geometry_msgs/Point SHOULDER_LEFT_COORD
geometry_msgs/Point ELBOW_RIGHT_COORD
geometry_msgs/Point ELBOW_LEFT_COORD
geometry_msgs/Point HAND_RIGHT_COORD
geometry_msgs/Point HAND_LEFT_COORD
geometry_msgs/Point HIP_RIGHT_COORD
geometry_msgs/Point HIP_LEFT_COORD
#geometry_msgs/Point KNEE_RIGHT_COORD
#geometry_msgs/Point KNEE_LEFT_COORD
#geometry_msgs/Point FOOT_RIGHT_COORD
#geometry_msgs/Point FOOT_LEFT_COORD

#Fine coordinate della kinect.

sensor_msgs/Image img

#se il viso dell'utente è di fronte al sensore
#face_front = true
#bool face_front

